#!/bin/bash

do_start() {
  cd /app/judge/src
  export GOPATH=/app/judge
  go run main.go >> /app/stdout.log 2>>/app/stderr.log &
}
do_stop() {
  killall -15 main
}
do_status() {
  if [[ $(ps aux|grep main| wc -l) -ne 1 ]]; then
    echo started
  else
    echo stopped
  fi
}
case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: $0 start|stop|restart" >&2
    exit 1
    ;;
esac
